### PR TITLE
Google api

### LINKED ISSUE #1: Google API
Hi,
I just found your project and it would be a nice improvement for my current toy project.
Are you willing to continue with it?
I'll try to open a pull request with a simple version for Google translate this week.

### PR DESCRIPTION
**Pull request by janosimas**
fix #1 

This is a working implementation for a GoogleV2 API, it's a only a first version.

## Working
- translate
- detect language
- API key (not recommended by google)
- translate without specifying input language

## Not working 
- other authorization methods

### CODE REVIEW

**Comment by aunetx** [comment]
Great, do you think it would be ready to be merged?

**Comment by janosimas** [comment]
It's a first working version.
I'd like to revisit some of the authorization methods but it can be done latter.

**Comment by aunetx** [comment]
OK cool! Take your time and sorry for not being very responsive :)

**Comment by janosimas** [comment]
@aunetx I'll merge this if it's ok for you.

**Comment by aunetx** [comment]
Yeah of course! Good job :)

**Pull request merged**
